Repository andela/tesla-ah, pull requests merged in 2019-06, with the labels that each got.

#4 #166413869 Convert project from es5 to es6
  .babelrc
  .env.example
  .gitignore
  config/index.js
  config/passport.js
  index.js
  models/User.js
  package.json
  routes/api/index.js
  routes/api/users.js
  routes/index.js
  src/api/controllers/auth.js
  src/api/routes/authRouter.js
  src/api/routes/index.js
  src/index.js
  src/middleware/globalMiddleware.js
  yarn.lock
Labels: WIP

#6 #166240982 Re-setup of Eslint and Airbnb as Style guide
  .eslintrc.js
  package-lock.json
  package.json
  yarn.lock
Labels: Needs Merge

#1 #166240980 Integrate TravisCI with readme badge
  .travis.yml
  README.md
  package.json
  test/auth.js
  yarn.lock
Labels: Needs Merge

#7 #166240985 - Setup for Unit Testing
  package.json
  yarn.lock
Labels: Needs Review

#10 create a coverage script and install all related dependencies
  .gitignore
  .travis.yml
  Procfile
  README.md
  package.json
  yarn.lock
Labels: Needs Review

#8 #166240987 setup API documentation using swagger
  package.json
  src/index.js
  swagger.json
  yarn.lock
Labels: Needs Merge

#9 #166240981 Configure Postgres as db engine
  .env.example
  .eslintrc.json
  README.md
  package.json
  src/config/environments.js
  src/db/index.js
  src/helpers/dbUrlParser.js
  src/index.js
  yarn.lock
Labels: Needs Review

#16 #166240981 configure sequelize-cli with es6
  .env.example
  .sequelizerc
  package.json
  src/config/config.js
  src/config/environments.js
  src/db/index.js
  src/helpers/dbUrlParser.js
  src/index.js
  src/sequelize/models/index.js
  yarn.lock
Labels: Needs Merge

#14 #166240989 Verfy token
  .gitignore
  README.md
  package.json
  src/api/helpers/Token.helper.js
  src/config/config.js
  src/helpers/dbUrlParser.js
  src/index.js
  src/middleware/auth.js
  src/sequelize/models/index.js
  swagger.json
  yarn.lock
Labels: Needs Merge

#17 chore(maintenability): add code climate
  README.md
Labels: Needs Merge

#18 #166240991 Add user registration validation errors
  .env.example
  .travis.yml
  package.json
  src/api/routes/authRouter.js
  src/config/config.js
  src/helpers/Token.helper.js
  src/helpers/userSchema.js
  src/index.js
  src/middleware/userValidations.js
  src/middleware/validUser.js
  src/sequelize/migrations/20190612225745-create-user.js
  src/sequelize/models/index.js
  src/sequelize/models/user.js
  src/sequelize/seeders/20190611101225-test-user.js
  test/auth.js
  yarn.lock
Labels: Needs Merge

#19 #166240995 User profile creation
  .travis.yml
  README.md
  package.json
  src/api/controllers/profiles.js
  src/api/routes/authRouter.js
  src/api/routes/index.js
  src/api/routes/profilesRouter.js
  src/api/routes/userRouter.js
  src/config/config.js
  src/helpers/Token.helper.js
  src/helpers/validationSchemas.js
  src/index.js
  src/middleware/auth.js
  src/middleware/globalMiddleware.js
  src/middleware/userExists.js
  src/middleware/usernameExists.js
  src/middleware/validateBody.js
  src/sequelize/migrations/20190613144226-create-user.js
  src/sequelize/models/user.js
  swagger.json
  test/auth.test.js
  test/profiles.test.js
Labels: Needs Merge

#20 #166240990 Send a verification link after a successful registration
  .env.example
  .gitignore
  .travis.yml
  package.json
  src/api/controllers/auth.js
  src/api/routes/authRouter.js
  src/helpers/MailTemplate.helper.js
  src/helpers/SendMail.helper.js
  src/helpers/Token.helper.js
  src/helpers/dbUrlParser.js
  src/helpers/hashHelper.js
  src/index.js
  src/middleware/validUser.js
  src/middleware/validateGender.js
  src/sequelize/migrations/20190612172050-create-user.js
  src/sequelize/migrations/20190612225745-create-user.js
  src/sequelize/seeders/20190611101225-test-user.js
  swagger.json
  test/auth.test.js
  test/hash.test.js
  test/mailTemplate.test.js
  yarn.lock
Labels: Needs Merge

#22 #166240992 User SignOut
  src/api/controllers/auth.js
  src/api/routes/authRouter.js
  src/config/config.js
  src/index.js
  src/middleware/droppedToken.js
  src/sequelize/migrations/20190611082539-create-blacklist.js
  src/sequelize/migrations/20190611134750-create-blacklist.js
  src/sequelize/models/blacklist.js
  swagger.json
  test/auth.test.js
Labels: Needs Review

#24 #166240996 - CRUD articles With API Documentation and Tests
  package.json
  src/api/controllers/articlesController.js
  src/api/controllers/auth.js
  src/api/routes/articlesRouter.js
  src/api/routes/index.js
  src/helpers/articlesHelper.js
  src/helpers/validationSchema.js
  src/middleware/checkOwner.js
  src/middleware/validations.js
  src/sequelize/migrations/20190612225745-create-user.js
  src/sequelize/migrations/20190613144226-create-user.js
  src/sequelize/migrations/20190613355309-create-article.js
  src/sequelize/models/article.js
  src/sequelize/models/user.js
  src/sequelize/seeders/20190611101225-test-user.js
  swagger.json
  test/article.js
  test/mock/articles.js
  test/mock/signup.js
  yarn.lock
Labels: Needs Review

#25 #166240993 Password reset
  .env.example
  package.json
  src/api/controllers/auth.js
  src/api/routes/authRouter.js
  src/helpers/emailTemplete.js
  src/helpers/hashHelper.js
  src/middleware/resetValidation.js
  src/sequelize/seeders/20190611101225-test-user.js
  swagger.json
  test/passwordreset.test.js
  yarn.lock
Labels: Needs Merge

#26 #166240994 Enable social login
  .env.example
  .travis.yml
  package.json
  src/api/controllers/socialLogin.js
  src/api/routes/authRouter.js
  src/api/routes/index.js
  src/config/passportSetup.js
  src/helpers/destroyUser.js
  src/index.js
  src/middleware/socialAccountExists.js
  src/middleware/socialTest.js
  src/middleware/userExists.js
  src/middleware/usernameExists.js
  test/auth.test.js
  test/passwordreset.test.js
  yarn.lock
Labels: Needs Merge

#35 #166241008: feat(article): user should get article read time
  package.json
  src/api/controllers/articlesController.js
  src/helpers/ReadTime.helper.js
  src/middleware/droppedToken.js
  src/sequelize/migrations/20190612225745-create-user.js
  src/sequelize/migrations/20190613144226-create-user.js
  src/sequelize/migrations/20190617175548-create-user.js
  src/sequelize/models/user.js
  test/readtime.test.js
  yarn.lock
Labels: Needs Merge

#37 #166705699 - Get an error for the unavailable URL
  src/index.js
  src/sequelize/seeders/20190611101225-test-user.js
  test/article.test.js
  test/index.test.js
Labels: Needs Merge

#31 #166240992 Bug fixed for uncovered test.
  src/api/controllers/auth.js
  src/sequelize/seeders/20190618062925-test-user.js
  swagger.json
  test/auth.test.js
Labels: Needs Merge

#34 #166729093 Enable user to login
  .env.example
  package.json
  src/api/controllers/auth.js
  src/api/routes/authRouter.js
  src/helpers/validationSchemas.js
  src/index.js
  src/middleware/resetValidation.js
  src/middleware/validateBody.js
  src/sequelize/seeders/20190618062925-test-user.js
  swagger.json
  test/auth.test.js
Labels: Needs Merge

#28 #166241001 User should be able to like or dislike and article
  .codeclimate.yml
  .sequelizerc
  package.json
  src/api/controllers/articlesController.js
  src/api/routes/articlesRouter.js
  src/helpers/articlesHelper.js
  src/helpers/validationSchema.js
  src/helpers/validationSchemas.js
  src/middleware/auth.js
  src/middleware/checkOwner.js
  src/middleware/validateBody.js
  src/sequelize/migrations/20190612225745-create-user.js
  src/sequelize/migrations/20190613144226-create-user.js
  src/sequelize/migrations/20190613355309-create-article.js
  src/sequelize/migrations/20190617104354-rename-articles-table.js
  src/sequelize/migrations/20190617122836-rename-authorid.js
  src/sequelize/migrations/20190617175548-create-user.js
  src/sequelize/migrations/20190619090814-create-like-dislike.js
  src/sequelize/models/article.js
  src/sequelize/models/likedislike.js
  src/sequelize/models/user.js
  swagger.json
  test/articles.test.js
Labels: Needs Merge

#41 #166241005 Integrate articles pagination
  src/api/controllers/articlesController.js
  src/api/routes/authRouter.js
  src/index.js
  src/sequelize/migrations/20190612172050-create-user.js
  src/sequelize/models/user.js
  swagger.json
  test/auth.test.js
  yarn.lock
Labels: Needs Merge

#32 #166241000 Build endpoints for comments on articles (CRUD)
  .env.example
  .travis.yml
  src/api/controllers/auth.js
  src/api/controllers/comments.js
  src/api/controllers/socialLogin.js
  src/api/routes/articlesRouter.js
  src/helpers/destroyUser.js
  src/helpers/hashSuperUserPsw.js
  src/helpers/validationSchemas.js
  src/middleware/auth.js
  src/middleware/validComment.js
  src/middleware/validations.js
  src/sequelize/migrations/20190617104354-rename-articles-table.js
  src/sequelize/migrations/20190617110332-create-comment.js
  src/sequelize/migrations/20190617122836-rename-authorid.js
  src/sequelize/migrations/20190617142742-add-comment-user-association.js
  src/sequelize/migrations/20190617142756-add-comment-article-association.js
  src/sequelize/migrations/20190617142809-add-comment-comment-association.js
  src/sequelize/migrations/20190617184505-add-isAdmin-field-users.js
  src/sequelize/migrations/20190619094032-add-slug-in-comments.js
  src/sequelize/models/article.js
  src/sequelize/models/comment.js
  src/sequelize/models/user.js
  src/sequelize/seeders/20190618062925-test-user.js
  src/sequelize/seeders/20190620204605-articles-test.js
  swagger.json
  test/auth.test.js
  test/comments.test.js
Labels: Needs Review

#40 #166241006 - Listing the Users profile
  src/api/controllers/profiles.js
  src/api/routes/profilesRouter.js
  swagger.json
  test/profiles.test.js
Labels: Needs Review

#44 #166740799 User can upload images
  .env.example
  package.json
  src/api/controllers/auth.js
  src/api/controllers/profiles.js
  src/api/routes/authRouter.js
  src/api/routes/userRouter.js
  src/handlers/cloudinary.js
  src/handlers/multer.js
  src/helpers/uploadHelper.js
  src/index.js
  test/auth.test.js
  test/mock/sample.png
  test/profiles.test.js
  yarn.lock
Labels: Needs Merge

#39 #166240997 User is able to create ratings on Article.
  src/api/controllers/auth.js
  src/api/controllers/ratingController.js
  src/api/routes/articlesRouter.js
  src/helpers/validationSchemas.js
  src/middleware/droppedToken.js
  src/middleware/slugExist.js
  src/sequelize/migrations/20190619100157-create-article-ratings.js
  src/sequelize/models/articleratings.js
  test/ratings.test.js
Labels: Needs Merge

#46 Save read time on article creation and update
  src/api/controllers/articlesController.js
  src/helpers/articlesHelper.js
  src/sequelize/migrations/20190613355309-create-article.js
  src/sequelize/migrations/20190620145553-add-readtime.js
  src/sequelize/models/article.js
  test/articles.test.js
  test/comments.test.js
  test/ratings.test.js
Labels: Needs Merge

#45 #166740833 User can get likes and dislikes for an article
  src/api/controllers/articlesController.js
  src/api/routes/articlesRouter.js
  test/articles.test.js
Labels: Needs Merge

#42 #166240999 Generate Rating Report on a specific article
  .codeclimate.1.yml
  package.json
  src/api/controllers/ratingContoller.js
  src/api/routes/index.js
  src/api/routes/ratingsRouter.js
  src/helpers/destroyTables.js
  src/index.js
  src/sequelize/models/articleratings.js
  src/sequelize/seeders/20190618062925-test-user.js
  src/sequelize/seeders/20190618152420-articleRatings.js
  swagger.json
  test/ratingscarc.test.js
  yarn.lock
Labels: Needs Merge

#48 feature(follow and unfollow):user can follow and unfollow each other
  .env.example
  .gitignore
  .travis.yml
  package.json
  src/api/controllers/auth.js
  src/api/controllers/profiles.js
  src/api/routes/authRouter.js
  src/api/routes/profilesRouter.js
  src/config/config.js
  src/index.js
  src/middleware/shareArticle.js
  src/middleware/validUser.js
  src/sequelize/migrations/20190617202025-create-follows.js
  src/sequelize/migrations/20190620145553-add-readtime.js
  src/sequelize/models/follows.js
  src/sequelize/seeders/20190618062925-test-user.js
  src/sequelize/seeders/20190620204605-articles-test.js
  swagger.json
  test/auth.test.js
  test/profiles.test.js
  test/ratingscarc.test.js
Labels: Needs Merge

#49 #166241012 Build api endpoints for likes and dislikes on comments
  package.json
  src/api/controllers/bookmark.js
  src/api/controllers/comments.js
  src/api/routes/articlesRouter.js
  src/middleware/checkLikesDislikes.js
  src/sequelize/migrations/20190619090814-create-like-dislike.js
  src/sequelize/migrations/20190624081558-add-commentId-likeDislike.js
  src/sequelize/models/likedislike.js
  src/sequelize/seeders/20190620204605-articles-test.js
  swagger.json
  test/comments.test.js
Labels: Needs Merge

#51 #166241014 - Add moderator and admin roles
  .env.example
  src/api/controllers/auth.js
  src/api/controllers/comments.js
  src/api/controllers/profiles.js
  src/api/routes/userRouter.js
  src/middleware/auth.js
  src/middleware/checkOwner.js
  src/sequelize/migrations/20190624093422-add-admin-moderator.js
  src/sequelize/models/user.js
  src/sequelize/seeders/20190618062925-test-user.js
  src/sequelize/seeders/20190620204605-articles-test.js
  test/articles.test.js
  test/auth.test.js
  test/profiles.test.js
Labels: Needs Merge

#52 feat(report-article): Enable user to report an article
  .env.example
  .eslintrc.json
  .travis.yml
  package.json
  src/api/controllers/articlesController.js
  src/api/controllers/ratingContoller.js
  src/api/controllers/ratingController.js
  src/api/routes/articlesRouter.js
  src/api/routes/ratingsRouter.js
  src/config/config.js
  src/helpers/destroyTables.js
  src/index.js
  src/middleware/slugExist.js
  src/sequelize/migrations/20190624102025-create-reportedarticles.js
  src/sequelize/models/reportedarticles.js
  src/sequelize/seeders/20190620204605-articles-test.js
  swagger.json
  test/articles.test.js
  test/index.test.js
  yarn.lock
Labels: Needs Merge

#57 #166241018 Implement comments edit track history
  .codeclimate.1.yml
  .codeclimate.yml
  src/api/controllers/comments.js
  src/api/routes/articlesRouter.js
  src/sequelize/migrations/20190625184332-create-comments-history.js
  src/sequelize/models/commentshistory.js
  swagger.json
  test/comments.test.js
Labels: Needs Merge

#58 feat(block-an-article): Enable Super admin or Moderator to block article
  package.json
  src/api/controllers/articlesController.js
  src/api/routes/articlesRouter.js
  src/helpers/articlesHelper.js
  src/helpers/destroyTables.js
  src/helpers/validationSchemas.js
  src/middleware/articleNotBlocked.js
  src/middleware/auth.js
  src/middleware/blockedarticleExist.js
  src/middleware/isThisArticleBlocked.js
  src/middleware/slugExist.js
  src/sequelize/migrations/20200624102025-create-blockedarticle.js
  src/sequelize/migrations/20210624081558-add-blocked-article.js
  src/sequelize/models/article.js
  src/sequelize/models/blockedarticle.js
  src/sequelize/seeders/20190618062925-test-user.js
  src/sequelize/seeders/20190620204605-articles-test.js
  swagger.json
  test/articles.test.js
  test/profiles.test.js
Labels: Needs Merge

#59 #166885987 Fix expired tokens blacklisting logic
  .codeclimate.yml
  package.json
  src/api/controllers/auth.js
  src/api/controllers/profiles.js
  src/api/routes/authRouter.js
  src/helpers/Token.helper.js
  src/helpers/purgeDeadTokens.js
  src/index.js
  src/middleware/auth.js
  src/middleware/checkOwner.js
  src/middleware/droppedToken.js
  src/sequelize/migrations/20190611082539-create-blacklist.js
  src/sequelize/migrations/20190611134750-create-blacklist.js
  src/sequelize/migrations/20190627081610-add-iat-to-blaclist.js
  src/sequelize/models/blacklist.js
  test/articles.test.js
  test/profiles.test.js
  test/purge.test.js
  yarn.lock
Labels: Needs Merge

#53 #166241007 - Search Functionality Added to Authors Haven
  package.json
  src/api/controllers/articlesController.js
  src/api/routes/articlesRouter.js
  src/middleware/paginate.js
  src/middleware/search.js
  swagger.json
  test/comments.test.js
  test/paginate.test.js
  test/search.test.js
Labels: Needs Merge
